app/protests/forms.py
from app.helpers import FlaskFormMixin
from flask_wtf import RecaptchaField, FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Email, ValidationError, Required
import re
import datetime


data_required_with_message = DataRequired(message="This field is required")

def validate_date(form, field):
    date_protest_is_happening = field.data
    date_today = datetime.datetime.utcnow().date()
    if date_today > date_protest_is_happening:
        raise ValidationError("Protest must be organized for a date later than today")
    
class CreateProtestForm(FlaskFormMixin):
    title = StringField("Title", validators=[
        data_required_with_message
    ])
    text = TextAreaField("Text", validators=[
        data_required_with_message
    ])
    date = DateField("Date happening", validators=[
        data_required_with_message,
        validate_date
    ])
    submit = SubmitField("Submit")

class RegisterForProtestForm(FlaskForm):
    recaptcha = RecaptchaField()
    submit = SubmitField("Submit")

app/protests/__init__.py
from app.protests.routes import bp as protest_blueprint

app/protests/routes.py
from app.protests.forms import CreateProtestForm, RegisterForProtestForm
from app.models import Protest, User, Protestor
from flask import flash, render_template, redirect, url_for, request
from flask_login import current_user
from app import db
from app.helpers import(
    user_must_be_authenticated,
    commit_items_to_session,
    VerifyProtestExistence 
)
from sqlalchemy.sql.expression import func as sqlalchemy_func
from flask import Blueprint


bp = Blueprint("protest", __name__, template_folder="templates")


# Url Prefix for these routes is /protest

# /protest/create

@bp.route("/create", methods=["POST", "GET"])
@user_must_be_authenticated
def create():
    form = CreateProtestForm()
    if not form.validate_on_submit():
        return render_template("create_protest.html", form=form)
    title, text, date = form.get_attributes("title", "text", "date")
    p = Protest(title=title, text=text, date_happening=date)
    current_user.start_protest(p)
    commit_items_to_session(p)
    return redirect(url_for("protest.by_id", id=p.id))

# /protest/random
# This would create a lot of overhead in a large system

@bp.route("/random", methods=["GET"])
def random():
    random_protest = Protest.query.order_by(sqlalchemy_func.random()).first()
    return redirect(url_for("protest.by_id", id=random_protest.id))

# /protest/<id>

@bp.route("/<id>", methods=["GET"])
@VerifyProtestExistence(message="aa")
def by_id(protest):
    return render_template("protest.html", protest=protest)

#/protest/<id>/register

@bp.route("/<id>/register", methods=["GET", "POST"])
@VerifyProtestExistence(message="Unable to register for protest")
def register_by_id(protest):
    form = RegisterForProtestForm()
    if not form.validate_on_submit():
        return render_template("register_for_protest.html", form=form)
    unique_protestor = request.cookies.get("unique_protestor", False)
    if not Protestor.is_unique(unique_protestor, protest.id):
        flash("You have already registered for that protest")
        return redirect(url_for("index"))
    protestor = Protestor(
        cookie_unique=unique_protestor,
        protest_id=protest.id
    )
    commit_items_to_session(protestor)
    return redirect(url_for("protest.by_id", id=protest.id))

app/protests/templates/create_protest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Protest</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css" type="text/css">
    <style>
      .map {
        height: 400px;
        width: 100%;
      }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>

</head>
<body>
    {% with errors = get_flashed_messages() %}
    {% if errors %}
        <ul>
            {% for message in errors %}
                <li style="color: red;">[{{message}}]</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br>
            {{ form.title(size=32) }}
            {% for error in form.title.errors %}
                <span style="color: red;">[{{error}}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.text.label }}<br>
            {{ form.text(size=1028) }}
            {% for error in form.text.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.date.label }}<br>
            {{ form.date() }}
            {% for error in form.date.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
    <div id="map" class="map"></div>
</body>
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>
<script type="text/javascript" src="/js/map.js"></script>
<script>getLocation()</script>
</html>

app/protests/templates/protest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ protest.title }}</title>
</head>
<body>
    <p><h1>Title</h1>{{ protest.title }}</p>
    <p><h1>Id</h1>{{ protest.id }}</p>
    <p><h1>Text</h1>{{ protest.text }}</p>
    <p><h1>Number of protestors</h1>{{ protest.number_of_protestors }}</p>
    <a href="{{url_for('protest.register_by_id', id=protest.id)}}">Register for protest</a>
</body>
</html>

app/protests/templates/register_for_protest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register for protest</title>
</head>
<body>
    <form action="" method="post" id="form_submit" novalidate>
        {{ form.hidden_tag() }}
        {{ form.recaptcha }}
        {% for error in form.recaptcha.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
        {{ form.submit() }}
    </form>
</body>
</html>